# Generated by Django 2.0.5 on 2018-05-19 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('sigla', models.CharField(max_length=64, null=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, null=True)),
                ('data_final', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
