# Generated by Django 2.0.5 on 2018-05-18 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_final',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
