# Generated by Django 2.0.5 on 2018-05-19 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('project_init', models.CharField(max_length=64, null=True)),
                ('project_start_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('project_final_date', models.DateField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
