# Generated by Django 2.0.4 on 2018-04-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='sigla',
        ),
    ]
