# Generated by Django 2.0.4 on 2018-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0002_remove_projeto_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='sigla',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
