# Generated by Django 2.0.5 on 2018-05-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0002_auto_20180518_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='sigla',
            field=models.CharField(default='', max_length=64),
        ),
    ]
