# Generated by Django 2.0.5 on 2018-05-19 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0007_auto_20180518_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_final',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
