# Generated by Django 2.0.5 on 2018-05-19 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctsp', '0010_auto_20180519_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_final',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='sigla',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
