# Generated by Django 2.0.4 on 2018-04-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrosDoTime',
            fields=[
                ('id_membro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_membro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=30)),
                ('membros_projeto', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='membrosdotime',
            name='idProjeto_membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Projeto'),
        ),
    ]
